import "ritthickclone/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import justlogo from "../app/assets/justlogo.svg"
import { TRPCReactProvider } from "ritthickclone/trpc/react";

export const metadata: Metadata = {
  title: "Airtable",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/justlogo.svg" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
